[package]
name = "epics-tools"
version = "0.1.0"
authors = [ "Ricardo CÃ¡rdenes <ricardo.cardenes@noirlab.edu>" ]
edition = "2021"

[dependencies]
clap = "4.3"
epics-ca = "0"
futures = "0"
tokio = { version = "1", features = [ "full" ] }
